import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import os

def generate_improved_rfi_diagnostic(dataset_file='training_results/astro_rfi_test_residuals.npz', num_examples=3):
    if not os.path.exists(dataset_file):
        print(f"Error: {dataset_file} not found.")
        return

    # Load the new data format
    data = np.load(dataset_file)
    inputs = data['inputs']          # S' (Original signal)
    rfi_error = data['rfi_error']    # T_ng - T_ng_hat (Missed RFI)
    predictions = data['predictions'] # T_ng_hat (Model's RFI)
    
    # Calculate the recovered Sky Signal: Tg_hat = S' - T_ng_hat
    tg_hat = inputs - predictions

    indices = np.random.choice(len(inputs), num_examples, replace=False)

    for idx in indices:
        S = inputs[idx]
        error_signal = rfi_error[idx]
        clean_sky_estimate = tg_hat[idx]
        
        # --- FOCUS LOGIC ---
        # We find the peak of the original RFI by looking at the model's prediction
        t0_detected = np.argmax(np.abs(predictions[idx]))
        window_half_width = 100 
        
        start = max(0, t0_detected - window_half_width)
        end = min(len(S), t0_detected + window_half_width)
        
        # We want to check if the clean_sky_estimate is Gaussian inside the RFI zone
        # data_rfi_zone = clean_sky_estimate[start:end]
        # And check it outside the RFI zone
        # data_clean_zone = np.concatenate([clean_sky_estimate[:start], clean_sky_estimate[end:]])
        # -- Adding this section to see region before and after the RFI window --
        data_clean_zone = clean_sky_estimate[start:end]
        data_rfi_zone = S[start:end]

        # Statistical Tests on the Recovered Sky Signal
        _, p_clean = stats.shapiro(data_clean_zone[:5000]) # Shapiro-Wilk test
        _, p_rfi = stats.shapiro(data_rfi_zone)

        # Plotting
        fig = plt.figure(figsize=(15, 12))
        grid = fig.add_gridspec(3, 2, height_ratios=[1, 1, 1])

        # 1. Top Panel: Recovered Sky Signal with Window Highlight
        ax_top = fig.add_subplot(grid[0, :])
        ax_top.plot(S, color='lightgray', label='Original Input (S)', alpha=0.5)
        ax_top.plot(clean_sky_estimate, color='dodgerblue', label='Recovered Sky ($\hat{T}_g$)', alpha=0.8)
        ax_top.fill_between(range(start, end), -0.2, 0.2, color='crimson', alpha=0.1, label='Analysis Window')
        ax_top.set_title(f'Sample {idx}: Recovery Analysis (Window: {start} to {end})')
        ax_top.set_ylim(-0.2, 0.2)
        ax_top.legend(loc='upper right', ncol=3)

        # 3. Bottom Left: Histogram of Recovered Sky
        ax_hist = fig.add_subplot(grid[1, 0])
        sns.histplot(data_clean_zone, kde=True, ax=ax_hist, color='forestgreen', label='Outside Window', stat="density", alpha=0.4)
        sns.histplot(data_rfi_zone, kde=True, ax=ax_hist, color='crimson', label='Inside RFI Window', stat="density", alpha=0.4)
        ax_hist.set_title('PDF of Recovered Sky Signal')
        ax_hist.legend()

        # 4. Bottom Right: Q-Q Plot of Recovered Sky
        ax_qq = fig.add_subplot(grid[1, 1])
        stats.probplot(data_clean_zone, dist="norm", plot=ax_qq)
        ax_qq.get_lines()[0].set_markerfacecolor('forestgreen')
        ax_qq.get_lines()[0].set_label(f'After RFI removal (p={p_clean:.2e})')
        
        (osm, osr), _ = stats.probplot(data_rfi_zone, dist="norm", plot=None)
        ax_qq.scatter(osm, osr, color='crimson', s=15, label=f'Before RFI removal (p={p_rfi:.2e})', alpha=0.6)
        
        ax_qq.set_title('Normal Q-Q Plot (Recovered Sky)')
        ax_qq.legend()

        plt.tight_layout()
        plt.savefig(f"recovery_diagnostic_test_{idx}.png", dpi=300)
        plt.close()
        print(f"Generated diagnostic for sample {idx}: p-value in RFI zone = {p_rfi:.4f}")

if __name__ == "__main__":
    sns.set_theme(style="whitegrid")
    # Point to the specific residuals file generated by training script
    generate_improved_rfi_diagnostic(dataset_file='training_results/astro_rfi_test_residuals.npz')
